swagger: "2.0"
info:
  version: "0.0.1"
  title: BeDeLOS - BDL Online Spielberichtsbogen
# basePath prefixes all resource paths
basePath: /bedelos
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - text/plain
  - text/html
  - application/json

paths:

  /info:
    x-swagger-router-controller: bedelos.Info
    get:
      produces:
        - text/html
      description:
        Displays some information on the BeDeLOS server status
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /spielplan:
    x-swagger-router-controller: bedelos.Spielplan
    get:
      produces:
        - text/html
      description:
        Displays the spielplan
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: query
          required: true
        - name: runde
          type: string
          description: Vorrunde (vr) oder Rückrunde (rr)
          in: query
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /teams:
    x-swagger-router-controller: bedelos.Teams
    get:
      produces:
        - text/html
      description:
        Displays a list of all teams
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: query
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /ergebnis:
    x-swagger-router-controller: bedelos.Result
    post:
      consumes:
        - multipart/form-data
      description:
        Stores the game result and picture uploaded from an mobile device
      parameters:
        - name: tcHeim
          type: string
          description: Emailadress of home team captain
          in: formData
          required: false
        - name: tcGast
          type: string
          description: Emailadress of guest team captain
          in: formData
          required: false
        - name: spielId
          type: string
          description: ID of the Game
          in: formData
          required: false
        - name: test
          type: boolean
          description: inidcates testmode
          in: query
          required: false
        - name: picture
          in: formData
          description: The picture taken by the mobile device
          required: false
          type: file
          minLength: 1
          maxLength: 5000000  # ~5MB
        - name: res
          in: formData
          description: Result object as JSON serialized string object
          required: true
          type: string
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /inbox:
    x-swagger-router-controller: bedelos.Inbox
    get:
      produces:
        - text/html
      description:
        Displays the Inbox
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /inbox/{gameId}:
    x-swagger-router-controller: bedelos.InboxDetails
    get:
      produces:
        - text/html
      description:
        Displays the Inbox
      parameters:
        - name: gameId
          type: string
          description: Inbox Game Id
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"



# complex objects have schema definitions
definitions:
  HTML:
    type: string