swagger: "2.0"
info:
  version: "0.0.1"
  title: BeDeLOS - BDL Online Spielberichtsbogen
# basePath prefixes all resource paths
basePath: /bedelos
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - text/plain
  - text/html
  - application/json

paths:

  /info:
    x-swagger-router-controller: bedelos.Info
    get:
      produces:
        - text/html
      description:
        Displays some information on the BeDeLOS server status
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /spielplan:
    x-swagger-router-controller: bedelos.Spielplan
    get:
      produces:
        - text/html
      description:
        Displays the spielplan
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: query
          required: true
        - name: runde
          type: string
          description: Vorrunde (vr) oder Rückrunde (rr)
          in: query
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /spielplan/generator/spiel/{spielindex}:
    x-swagger-router-controller: bedelos.SpielplanGenerator
    get:
      produces:
        - text/html
      description:
        Displays an Input Form to enter new Games to a new Spielplan
      parameters:
        - name: spielindex
          type: string
          description: Index of game
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"
    delete:
      produces:
        - text/html
      description:
        Deletes a Game from the new Spielplan
      parameters:
        - name: spielindex
          type: string
          description: Index of game
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /spielplan/generator:
    x-swagger-router-controller: bedelos.SpielplanGenerator
    get:
      produces:
        - text/html
      description:
        Displays an Input Form to enter new Games to a new Spielplan
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"
    post:
      consumes:
        - application/json
      produces:
        - text/html
      description:
        Adds a new game to Spielplan
      parameters:
        - name: spiel
          in: body
          description: Spiel-Details
          required: true
          schema:
            $ref: "#/definitions/GameObject"
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"


  /teams:
    x-swagger-router-controller: bedelos.Teams
    get:
      produces:
        - text/html
      description:
        Displays a list of all teams
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: query
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /wertung/{gameId}:
    x-swagger-router-controller: bedelos.Wertung
    post:
      produces:
        - text/html
      description:
        Releases a Game in the Inbox
      parameters:
        - name: gameId
          type: string
          description: Inbox Game Id
          in: path
          required: true
        - name: name
          in: formData
          type: string
          description: Name
          required: true
        - name: value
          in: formData
          type: string
          description: Value
          required: true
        - name: pk
          in: formData
          type: string
          description: PrivateKey
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /teammanagement:
    x-swagger-router-controller: bedelos.Teammanagement
    get:
      produces:
        - text/html
      description:
        Handles a teammanagement page
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /teammanagement/add:
    x-swagger-router-controller: bedelos.PlayersAdd
    get:
      produces:
        - text/html
      description:
        Deletes a team member from team
      parameters:
        - name: name
          type: string
          description: Name
          in: query
          required: true
        - name: vorname
          type: string
          description: Base64 encoded first name
          in: query
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /teammanagement/delete:
    x-swagger-router-controller: bedelos.PlayersDelete
    get:
      produces:
        - text/html
      description:
        Deletes a team member from team
      parameters:
        - name: encname
          type: string
          description: Base64 encoded name
          in: query
          required: true
        - name: encvorname
          type: string
          description: Base64 encoded first name
          in: query
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /teammanagement/update:
    x-swagger-router-controller: bedelos.TeamUpdate
    post:
      consumes:
        - application/json
      produces:
        - text/html
      description:
        Updates team relevant information
      parameters:
      - name: team
        in: body
        description: Teaminformation
        required: true
        schema:
          $ref: "#/definitions/TeamPayload"
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /login:
    x-swagger-router-controller: bedelos.Authentication
    get:
      consumes:
        - application/json
      produces:
        - text/html
      description:
        Shows the login form
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"
    post:
      produces:
        - text/html
      description:
        Updates team relevant information
      parameters:
      - name: credentials
        in: body
        description: Login Credentials
        required: true
        schema:
          $ref: "#/definitions/OBJECT"
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"
    delete:
      consumes:
        - application/json
      produces:
        - text/html
      description:
        Updates team relevant information
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /changePassword/user/{username}:
    x-swagger-router-controller: bedelos.ChangePassword
    get:
      consumes:
        - application/json
      produces:
        - text/html
      parameters:
        - name: username
          type: string
          description: Username
          in: path
          required: true
      description:
        Shows the change password form
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /changePassword:
    x-swagger-router-controller: bedelos.ChangePassword
    post:
      produces:
        - application/json
      description:
        Updates team password
      parameters:
      - name: credentials
        in: body
        description: Login Credentials
        required: true
        schema:
          $ref: "#/definitions/OBJECT"
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"
        '480':
          description: Old Password not matching
          schema:
            $ref: "#/definitions/HTML"
        '481':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"
    delete:
      consumes:
        - application/json
      produces:
        - text/html
      description:
        Reset all passwords to default ones
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /map:
    x-swagger-router-controller: bedelos.Map
    get:
      produces:
        - text/html
      description:
        Displays a map of where to find the teams and their location
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /map/update:
    x-swagger-router-controller: bedelos.MapUpdate
    get:
      produces:
        - text/html
      description:
        Updates the map data for all teams
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /map/locations:
    x-swagger-router-controller: bedelos.MapLocations
    get:
      produces:
        - application/json
      description:
        Get locations array for the Google Map
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/ARRAY"

  /tabelle/liga/{liga}:
    x-swagger-router-controller: bedelos.Tables
    get:
      produces:
        - text/html
      description:
        Displays a list of all teams
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: path
          enum: ["oberliga", "bzLiga", "klnord", "klsued"]
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /statistik/liga/{liga}:
    x-swagger-router-controller: bedelos.Statistics
    get:
      produces:
        - text/html
      description:
        Displays a list of statistics on all players
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: path
          enum: ["oberliga", "bzLiga", "klnord", "klsued"]
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /admin/tables/update/{liga}:
    x-swagger-router-controller: bedelos.UpdateTables
    get:
      produces:
        - text/html
      description:
        Runs a scan on all game results and recalculates the table
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: path
          enum: ["all", "oberliga", "bzLiga", "klnord", "klsued"]
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /admin/statistik/update/{liga}:
    x-swagger-router-controller: bedelos.UpdateStatistics
    get:
      produces:
        - text/html
      description:
        Runs a scan on all game results and recalculates the statistics
      parameters:
        - name: liga
          type: string
          description: Liga ID
          in: path
          enum: ["all", "oberliga", "bzLiga", "klnord", "klsued"]
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /ergebnis:
    x-swagger-router-controller: bedelos.Result
    post:
      consumes:
        - multipart/form-data
      description:
        Stores the game result and picture uploaded from an mobile device
      parameters:
        - name: tcHeim
          type: string
          description: Emailadress of home team captain
          in: formData
          required: false
        - name: tcGast
          type: string
          description: Emailadress of guest team captain
          in: formData
          required: false
        - name: spielId
          type: string
          description: ID of the Game
          in: formData
          required: false
        - name: test
          type: string
          description: inidcates testmode
          in: formData
          required: false
        - name: picture
          in: formData
          description: The picture taken by the mobile device
          required: false
          type: file
          minLength: 1
          maxLength: 5000000  # ~5MB
        - name: res
          in: formData
          description: Result object as JSON serialized string object
          required: true
          type: string
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /inbox:
    x-swagger-router-controller: bedelos.Inbox
    get:
      produces:
        - text/html
      description:
        Displays the Inbox
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /{storage}/{gameId}:
    x-swagger-router-controller: bedelos.Details
    get:
      produces:
        - text/html
      description:
        Displays the the details of a game
      parameters:
        - name: gameId
          type: string
          description: Inbox Game Id
          in: path
          required: true
        - name: storage
          type: string
          description: can either be inbox or ergebnisse
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /inbox/{gameId}/release:
    x-swagger-router-controller: bedelos.InboxRelease
    get:
      produces:
        - text/html
      description:
        Releases a Game in the Inbox
      parameters:
        - name: gameId
          type: string
          description: Inbox Game Id
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /inbox/{gameId}/reject:
    x-swagger-router-controller: bedelos.InboxReject
    get:
      produces:
        - text/html
      description:
        Releases a Game in the Inbox
      parameters:
        - name: gameId
          type: string
          description: Inbox Game Id
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"

  /inbox/{gameId}/delete:
    x-swagger-router-controller: bedelos.InboxDelete
    get:
      produces:
        - text/html
      description:
        Delete a Game in the Inbox
      parameters:
        - name: gameId
          type: string
          description: Inbox Game Id
          in: path
          required: true
      responses:
        'default':
          description: Successful response
          schema:
            $ref: "#/definitions/HTML"



# complex objects have schema definitions
definitions:
  HTML:
    type: string
  OBJECT:
    type: object
  ARRAY:
    type: array
    items:
      type: array
      items:
        type: string
  TeamPayload:
    type: object
    description: Parameters for updating team relevant information
  GameObject:
    type: object
    description: Parameters for adding game to spielplan
  Credentials:
    type: object
    properties:
      name:
        type: string
      locale:
        type: string
